// Map zone/creek/city data — extracted verbatim from public/map-standalone.html
/* eslint-disable */
export const mzd={
  lake:{t:"Clear Lake: Main Lake Body",tags:['mtd','mts'],b:"The main lake body (~39,854 acres) is the largest natural freshwater lake entirely within California, ~500,000 years old. The lake has three named arms: the Upper Arm (NW), the Oaks Arm (east-central), and the Lower Arm (SE). Scotts Creek system enters via Rodman Slough at the north. Kelsey Creek enters the south shore at Clear Lake State Park.",s:[{l:"Area (GeoJSON)",v:"39,854 acres"},{l:"Upper Arm",v:"NW lobe, Scotts Cr. drainage"},{l:"Oaks Arm",v:"East-central, Schindler/Burns drainage"},{l:"Lower Arm",v:"SE, Seigler/Cache Cr. drainage"},{l:"USGS gauge",v:"Stn. 11450000, Lakeport pier"},{l:"HABs",v:"Severe, annual",c:"mdw"}]},
  thurston:{t:"Thurston Lake (Isolated Refuge)",tags:['mts','mtd'],b:"Hydrologically isolated from Clear Lake; supports a currently robust separate hitch population. Treated as a distinct demographic unit and critical conservation refuge by USFWS.",s:[{l:"Connection to Clear Lake",v:"None, isolated",c:"mdg"},{l:"Hitch status",v:"Robust (2020 survey)",c:"mdg"}]},
  usgs:{t:"USGS Rumsey Gauge, Stn. 11450000",tags:['mtd'],b:"Located on the LCVCD pier at Lakeport. Records lake level every 15 minutes since 1873. Zero Rumsey = 1,318.26 ft above sea level.",s:[{l:"Record since",v:"1873"},{l:"Fish monitoring",v:"Since 2017"},{l:"Latest report",v:"OFR 2025-1018",c:"mdg"}]}
};
export const mckd={
  rodman:{t:"Rodman Slough",tags:['mts','mtd'],b:"Receives the entire Scotts Creek watershed: Scotts Creek (~24% of lake inflow, 30 miles), Middle Creek, Clover Creek, and Alley Creek.",s:[{l:"Scotts Cr. inflow",v:"~24% of total"},{l:"System length",v:"Scotts Creek = 30 miles"}]},
  scotts_sys:{t:"Scotts Creek Watershed",tags:['mts','mtd'],b:"Scotts Creek (30 mi, ~24% of lake inflow) rises near Cow Mountain, flows SE through Scotts Valley picking up Middle Creek, then W through Bachelor Valley before turning NE into Rodman Slough.",s:[{l:"System entry",v:"Via Rodman Slough"},{l:"Scotts Cr. inflow",v:"~24% of total"}]},
  lyons:{t:"Lyons Creek",tags:['mts'],b:"Enters the northwest shore. Listed in historical hitch habitat documentation as a spawning tributary.",s:[{l:"Historical use",v:"Hitch spawning documented"}]},
  morrison:{t:"Morrison Creek",tags:['mts'],b:"Enters the northeast shoulder of the Upper Arm. Listed in USFWS SSA as a historical hitch spawning tributary.",s:[{l:"Historical spawning",v:"Documented (USFWS SSA)"}]},
  lucerne:{t:"Lucerne Creek",tags:['mts'],b:"Enters the northeast shore near the town of Lucerne.",s:[{l:"Adjacent town",v:"Lucerne"}]},
  forbes:{t:"Forbes Creek",tags:['mts','mtd'],b:"A 4.7-mile stream entering at Lakeport on the west shore. Adult hitch confirmed in the 2024 Lake County WPD survey.",s:[{l:"Length",v:"4.7 miles"},{l:"2024 WPD adults",v:"Confirmed April 18",c:"mdg"},{l:"2024 flow cutoff",v:"May 28",c:"mdw"}]},
  manning:{t:"Manning Creek",tags:['mts'],b:"Enters the southwest shore. Thompson Creek joins Manning upstream. CDFW confirmed adult hitch in 2024 and 2025.",s:[{l:"CDFW 2024 to 2025",v:"Adults confirmed",c:"mdg"},{l:"2023 sighting (BVR)",v:"~300 at Merritt Rd"}]},
  rumsey:{t:"Rumsey Slough",tags:['mts'],b:"Enters the south shore between Manning Creek and Adobe Creek. A historic channel of Thompson Creek also connected here.",s:[{l:"Drainage",v:"Big Valley corridor"}]},
  adobe:{t:"Adobe Creek",tags:['mts','mtd'],b:"Historically one of the two most important hitch spawning streams. Most frequented tributary in 2016, 2018, 2022, 2023, and 2025.",s:[{l:"Historical rank",v:"#2 most important spawning trib"},{l:"CDFW 2024 to 2025",v:"Adults confirmed",c:"mdg"},{l:"Barriers documented",v:"Multiple",c:"mdw"}]},
  mcgaugh:{t:"McGaugh Slough",tags:['mts'],b:"Enters the south shore. No adults observed in CDFW surveys 2024 to 2025.",s:[{l:"CDFW 2024 to 2025",v:"None observed",c:"mdw"}]},
  kelsey:{t:"Kelsey Creek",tags:['mts','mtd'],b:"The most important active spawning tributary. Most frequented in 2017, 2019, and 2020 (when all 1,672 hitch were observed exclusively here). USGS gauge and HOBO loggers deployed.",s:[{l:"USGS gauge",v:"Station 11449500",c:"mdg"},{l:"CDFW 2024 to 2025",v:"Adults confirmed",c:"mdg"},{l:"Main St. barrier",v:"Removal in progress",c:"mdg"},{l:"Groundwater orders",v:"Big Valley basin, 2024",c:"mdw"}]},
  cole:{t:"Cole Creek",tags:['mts'],b:"Enters just east of Kelsey Creek. The Cole Creek Restoration Project aims to restore 1.55 miles of hitch spawning habitat.",s:[{l:"Restoration project",v:"1.55 mi, funded",c:"mdg"},{l:"CDFW 2024",v:"Dry downstream, none",c:"mdw"}]},
  schindler:{t:"Schindler Creek",tags:['mts'],b:"Enters the east end of the Oaks Arm. 2024 WPD survey site: no fish observed.",s:[{l:"2024 WPD",v:"No fish observed",c:"mdw"}]},
  burns:{t:"Burns Valley Creek",tags:['mts'],b:"Enters the SE shore in the Lower Arm. In 2024, ~4,000 juvenile hitch and Sacramento blackfish were observed here alongside thousands of larvae.",s:[{l:"2024 WPD juveniles",v:"~4,000 confirmed",c:"mdg"},{l:"2024 WPD larvae",v:"Thousands observed",c:"mdg"},{l:"2024 flow cutoff",v:"June 14",c:"mdw"}]},
  thompson:{t:"Thompson Creek",tags:['mts','mtd'],b:"Joins Manning Creek upstream. CDFW confirmed adults in 2024 and 2025.",s:[{l:"CDFW 2024 to 2025",v:"Adults confirmed",c:"mdg"}]},
  hill:{t:"Hill Creek",tags:['mts'],b:"Joins McGaugh Slough upstream. No adults observed in 2024 to 2025 CDFW surveys.",s:[{l:"CDFW 2024 to 2025",v:"None observed",c:"mdw"}]},
  highland:{t:"Highland Creek",tags:['mts'],b:"Joins Adobe Creek upstream.",s:[{l:"System entry",v:"Via Adobe Creek"}]},
  seigler_sys:{t:"Seigler Canyon + Perini + Copsey + Clayton Creeks",tags:['mts'],b:"All documented spawning tributaries. Seigler Canyon was historically one of the best sites but no adults confirmed since ~2004. Copsey Creek had confirmed adults March to May 2024.",s:[{l:"Seigler last confirmed",v:"~2004; none since",c:"mdw"},{l:"Copsey 2024 WPD",v:"Adults confirmed Mar to May",c:"mdg"}]}
};

export const mcitd={
  lakeport:{t:"Lakeport: Lake County Seat",tags:['mtd'],b:"County seat of Lake County, first settled in 1855 and originally called Forbestown after blacksmith/wagon-maker William Forbes. Renamed Lakeport on June 14, 1861. The city sits on Clear Lake's western shore at 1,355 ft elevation and hosts the historic Lake County Courthouse Museum (built 1871). The USGS gauge at the municipal pier has recorded lake levels every 15 minutes since 1873.",s:[{l:"Population (2020)",v:"5,026"},{l:"Est. 2026",v:"5,138"},{l:"Founded",v:"1855 (as Forbestown)"},{l:"Renamed",v:"1861"},{l:"Elevation",v:"1,355 ft"},{l:"County seat since",v:"1861"}]},
  clearlake_city:{t:"Clearlake: Largest City in Lake County",tags:['mtd'],b:"The largest city in Lake County, incorporated on November 14, 1980. Originally known as Konocti, then Clearlake Highlands. Located on the SE shore of Clear Lake at 1,417 ft elevation. Historical homeland of the Pomo people, who named nearby Mount Konocti. The city includes Austin Park Beach, Redbud Park, and Burns Valley.",s:[{l:"Population (2020)",v:"16,685"},{l:"Incorporated",v:"Nov 14, 1980"},{l:"Elevation",v:"1,417 ft"},{l:"Area",v:"10.58 sq mi"}]},
  clearlake_oaks:{t:"Clearlake Oaks: NE Arm Community",tags:['mtd'],b:"Unincorporated CDP on the northeast shore of Clear Lake, 8 miles NW of the city of Clearlake. The post office opened in 1926 as 'Stubbs' (after local landowner Charles Stubbs), renamed to Clearlake Oaks in 1935. The original town site inland of State Route 20 was subdivided by the 1920s as a triangular fishing-cottage village around a central plaza.",s:[{l:"Population (2020)",v:"2,551"},{l:"Founded",v:"1926 (as Stubbs)"},{l:"Renamed",v:"1935"},{l:"Elevation",v:"1,335 ft"},{l:"Area",v:"2.1 sq mi"}]},
  kelseyville:{t:"Kelseyville: Pear Capital",tags:['mtd'],b:"Named after Andrew Kelsey, an early 1847 Anglo-American settler. First structures built in the 1850s. Kelsey Creek runs through the town and enters Clear Lake at its south shore, the single most important active hitch spawning tributary. Known as the 'Pear Capital of the World' through the 20th century; 85,000 tons of pears were processed in Lake County in 1999 alone. Hosts the annual Kelseyville Pear Festival.",s:[{l:"Population (2020)",v:"3,382"},{l:"Founded",v:"~1850s"},{l:"Nickname",v:"Pear Capital"},{l:"Elevation",v:"1,385 ft"}]},
  nice:{t:"Nice: North Shore Community",tags:['mtd'],b:"Small unincorporated lakeside community on the north shore of Clear Lake's Upper Arm. Named after the French Riviera city of Nice by early 20th-century developers marketing the area as a resort destination.",s:[{l:"Type",v:"Unincorporated CDP"},{l:"Location",v:"Upper Arm, N shore"}]},
  lucerne_town:{t:"Lucerne, 'Switzerland of America'",tags:['mtd'],b:"Unincorporated CDP on the NE shore of Clear Lake. Founded as a resort community in the early 1900s and nicknamed the 'Switzerland of America' for its lakefront mountain scenery. Home to the historic Lucerne Harbor and antique shops along State Route 20.",s:[{l:"Population (2020)",v:"~2,900"},{l:"Nickname",v:"Switzerland of America"},{l:"Type",v:"Unincorporated CDP"}]},
  upper_lake:{t:"Upper Lake: Historic North Community",tags:['mtd'],b:"Unincorporated community at the north end of Clear Lake, just upstream from Rodman Slough. Post office opened in 1872. Historically one of the earliest European-American settlements in Lake County.",s:[{l:"Post office",v:"Est. 1872"},{l:"Type",v:"Unincorporated"},{l:"Location",v:"N of Rodman Slough"}]}
};
